page 50102 "Explanation Rich Text"
{
    PageType = StandardDialog;
    Caption = 'Explanation';

    layout
    {
        area(Content)
        {
            group(General)
            {
                group(InstructionalText)
                {
                    ShowCaption = false;
                    InstructionalText = 'The explanacion of Financial Report generated by Azure OpenAI';
                }

                field(ExplanationText; ExplanationText)
                {
                    ApplicationArea = All;
                    ShowCaption = false;
                    Editable = true;
                    MultiLine = true;
                }
            }
        }
    }

    var
        ExplanationText: Text;

    procedure SetExplanationText(FromText: Text)
    begin
        ExplanationText := FromText;
    end;
}